name: Anderson auto test


on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: select tests on run
        required: true
        type: choice
        default: all
        options:
          - all
          - test_2


jobs:
  run-test:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Source code
        uses: actions/checkout@v4
      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run test
        run: pytest -v
      # - name: test_2
      #   if: "github."
