name: Anderson auto test


on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        type: choice
        default: all
        options:
          - all

permissions:
  contents: read
  pages: write
  id-token: write
  


jobs:
  run-test:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Source code
        uses: actions/checkout@v4
      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run test
        run: pytest -v --alluredir=allure-results
      - name: Store allure results
        uses: actions/upload-artifact@v4
        with: 
          name: allure-results
          path:
            allure-results
          retention-days: 1
      
  generation-report:
    runs-on: ubuntu-latest
    needs: run-test
    name: Generation report
    steps:
      - uses: actions/setup-java@v4
        with: 
          distribution: 'micrasoft'
          java-version: '25'
      - run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.35.1/allure-2.35.1.tgz && sudo tar -zxvf allure-2.35.1.tgz -C /opt/ && sudo ln -s /opt/allure-2.35.1/bin/allure /user/bin/allure
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - run: allure generate -c allure-results -o _site
      - name: Store genrated report
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path:
            _site
          retention-days: 1
  
  publish-report:
    runs-on: ubuntu-latest
    needs: generation-report
    name: Report publication
    steps: 
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - name: Upload Pages artefact
        uses: actions/upload-pages-artifact@v3
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v1.2.9
        
    
