name: Anderson auto test


on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: select tests on run
        required: true
        type: choice
        default: test_1
        options:
          - test_1
          - test_2


jobs:
  run-test:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Source code
        uses: actions/checkout@v4
      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: test_1
        if: "github.event.inputs.deplment_target == 'test_1'"
        run: pytest -v Tests/test_4.py::test_universal_management
      - name: test_2
        if: "github.event.inputs.deplment_target == 'test_2'"
        run: pytest -v Tests/test_4.py::test_clien_contracts
